CREATE TABLE IF NOT EXISTS triggerdata (
run_number INT NOT NULL,
version INT NOT NULL,
event_no INT NOT NULL,
seconds INT NOT NULL,
nanoseconds INT NOT NULL,
wr_event_no INT NOT NULL,
wr_seconds INT NOT NULL,
wr_nanoseconds INT NOT NULL,
enable_type INT NOT NULL,
enable_event_no INT NOT NULL,
enable_seconds INT NOT NULL,
enable_nanoseconds INT NOT NULL,
gate_id INT NOT NULL,
gate_type INT NOT NULL,
gate_id_bnb INT NOT NULL,
gate_id_numi INT NOT NULL,
gate_id_bnboff INT NOT NULL,
gate_id_numioff INT NOT NULL,
beam_seconds INT NOT NULL,
beam_nanoseconds INT NOT NULL,
trigger_type INT NOT NULL,
trigger_source INT NOT NULL,
cryo1_e_conn_0 TEXT NOT NULL,
cryo1_e_conn_2 TEXT NOT NULL,
cryo2_w_conn_0 TEXT NOT NULL,
cryo2_w_conn_2 TEXT NOT NULL,
cryo1_east_counts INT NOT NULL,
cryo2_west_counts INT NOT NULL,
mj_adder_source_east INT NOT NULL DEFAULT -1,
mj_adder_source_west INT NOT NULL DEFAULT -1,
flag_east INT NOT NULL DEFAULT -1,
delay_east INT NOT NULL DEFAULT -1,
flag_west INT NOT NULL DEFAULT -1,
delay_west INT NOT NULL DEFAULT -1,
PRIMARY KEY ( run_number, event_no )
);
